enum NG_FLIPEFFECTS {
	DISABLE_INPUT_FOR_TIME = 51,
	ENABLE_INPUT = 52,
	KILL_AND_OR_SET_LARA_ON_FIRE = 63,
	PLAY_CD_TRACK_ON_CHANNEL_1 = 68,
	FORCE_LARA_ANIMATION_0_255_OF_SLOT_ANIMATION = 77,
	FORCE_LARA_ANIMATION_256_512_OF_SLOT_ANIMATION = 80,
	REMOVE_WEAPONS_OR_FLARES_FROM_LARAS_HANDS = 83,
	DISARM_LARA = 96,
	PERFORM_TRIGGERGROUP_FROM_SCRIPT_IN_SPECIFIC_WAY = 118, // May be different in older TRNG versions (?)
	PLAY_CD_TRACK_ON_CHANNEL_2 = 129,
	ATTRACT_LARA_IN_DIRECTION_ON_GROUND = 134,
	SET_VOLUME_OF_AUDIO_TRACK_ON_CHANNEL = 133,
	ATTRACT_LARA_IN_DIRECTION_IN_AIR = 153,
	ATTRACT_LARA_IN_DIRECTION_ON_GROUND_AND_IN_AIR = 158,
	CAMERA_SHOW_BLACK_SCREEN_FOR_SECONDS_WITH_FINAL_CURTAIN_EFFECT = 367,
	CAMERA_SET_CINEMA_EFFECT_TYPE_FOR_SECONDS = 369,
	SET_LARA_HOLSTER_TYPE = 407
};

extern bool NGFlipEffect(unsigned short param, short extra, bool oneshot, bool skip_checks);