enum NG_ACTION_TYPE {
	TURN_ANIMATING_CLOCKWISE_BY_DEGREES = 1,
	PERFORM_FLIPEFFECT_ON_ITEM = 13,
	FORCE_ANIMATION_0_TO_31_ON_ITEM = 15,
	FORCE_ANIMATION_32_TO_63_ON_ITEM = 16,
	FORCE_ANIMATION_64_TO_95_ON_ITEM = 17,
	HURT_ENEMY = 38,
	FREEZE_ENEMY_FOR_SECONDS = 58,
	UNFREEZE_ENEMY_WITH_EFFECT = 59,
	MOVE_ITEM_UP_BY_UNITS_X8 = 63,
	MOVE_ITEM_DOWN_BY_UNITS_X8 = 64,
	MOVE_ITEM_WEST_BY_UNITS_X8 = 65,
	MOVE_ITEM_NORTH_BY_UNITS_X8 = 66,
	MOVE_ITEM_EAST_BY_UNITS_X8 = 67,
	MOVE_ITEM_SOUTH_BY_UNITS_X8 = 68,
};

extern void NGActionTrigger(unsigned short param, unsigned short extra);