enum NG_FLIPEFFECTS {
	DISABLE_INPUT_FOR_TIME = 51,
	PLAY_CD_TRACK_ON_CHANNEL_1 = 68,
	DISARM_LARA = 96,
	PLAY_CD_TRACK_ON_CHANNEL_2 = 129,
	ATTRACT_LARA_IN_DIRECTION_ON_GROUND = 134,
	SET_VOLUME_OF_AUDIO_TRACK_ON_CHANNEL = 133,
	ATTRACT_LARA_IN_DIRECTION_IN_AIR = 153,
	ATTRACT_LARA_IN_DIRECTION_ON_GROUND_AND_IN_AIR = 158,
	SET_LARA_HOLSTER_TYPE = 407
};

extern void NGFlipEffect(unsigned short param, short extra, bool oneshot);