#pragma once
#include "../../../global/types.h"

#define BADDY_SOMERSAULT_END_ANIMATION 4
#define BADDY_STAND_IDLE_ANIMATION 18
#define BADDY_STAND_TO_ROLL_LEFT_ANIMATION 24
#define BADDY_CROUCH_ANIMATION 29
#define BADDY_STAND_DEATH_ANIMATION 45
#define BADDY_STAND_TO_JUMP_RIGHT_ANIMATION 47
#define BADDY_STAND_TO_JUMP_FORWARD_ANIMATION 55
#define BADDY_MONKEY_TO_FREEFALL_ANIMATION 59
#define BADDY_CLIMB_4_CLICKS_ANIMATION 62
#define BADDY_CLIMB_3_CLICKS_ANIMATION 63
#define BADDY_CLIMB_2_CLICKS_ANIMATION 64
#define BADDY_JUMP_OFF_4_CLICKS_ANIMATION 65
#define BADDY_JUMP_OFF_3_CLICKS_ANIMATION 66
#define BADDY_BLIND_ANIMATION 68

void InitialiseBaddy(short item_number);
void BaddyControl(short item_number);
